name: test

on:
  push:
    branch: ['master']
  pull_request:
    branch: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Rust 🔧
        uses: dtolnay/rust-toolchain@stable

      - name: Run tests
        run: cargo test
